### ISSUE TITLE
TypeError: Cannot create property 'volume' on boolean 'false'.

### ISSUE THREAD

**Issue by LightenedLimited** [casperlofgren/stream-bot#4]
Im playing a radio thing, for me is !Pop, and it shows this when I do it, what do I do? 
![stream](https://cloud.githubusercontent.com/assets/26522050/24162802/e492925a-0e68-11e7-8b3b-0ffc19dc01e5.PNG)

**Comment by csprl** [comment]
Hi, unfortunately I don't support this anymore, mainly due to the code being very old and therefore not up-to-date. For example it still uses a regular Discord account and not a bot token as it should, and the discord.js version used is likely not going to work with the current Discord API endpoints either way. I recommend that you try to learn from this simple (but not very good!) code, and try to write your own. If that's too demanding, search for another bot which does the same (there're lots on GitHub).

**Comment by LightenedLimited** [comment]
Thanks Casper
